### ISSUE TITLE
feature request: supporting closures handlers

### ISSUE THREAD

**Issue by softprops** [kardeiz/reset-router#2]
I may be missing something but I believe the current interface for handlers only permits fn pointers which means that function implementations may only access global state. I'd like to propose a generic handler interface that can then be impl by things like closures and functions, and extensible for foreign types ( like an Application struct ).

I may have missed something from the docs. Let me know if this is actually currently possible today

**Comment by kardeiz** [comment]
Hi! You can use closures as well in the current version, though obviously this won't work with the proc_macro attribute setup. In the README example at the bottom, you could swap out a closure for the last `hello`. I'll put together a proper example soon. 

I think it makes sense to have a generic handler interface. I think I looked into using `hyper::service::Service` for the individual handlers, but there was some reason I couldn't use it. I'll look into this again.

**Comment by kardeiz** [comment]
I just pushed a new version [`0.6.4`](https://crates.io/crates/reset-router) that adds a `Service` trait. This is similar to Hyper's `Service` but takes `&self` instead of `&mut self` (immutability I think makes more sense in this case) and is more limited (e.g., takes `Request<Body>` instead of `Request<P> where P: Payload`).

You can now impl this `Service` trait for anything, although you are required to box it up yourself when using `RouterBuilder::add`. See the new example ([no_macros.rs](https://github.com/kardeiz/reset-router/blob/master/reset-router/examples/no_macros.rs)) for details (as well as a closure use example).
